---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: git-master
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-coronavirus-business-volunteer-form
      branch: master

  - name: git-master-gems-dockerfile
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/govuk-coronavirus-business-volunteer-form
      branch: master
      paths:
        - concourse/Dockerfile
        - Gemfile*

  - name: every-six-hours
    type: time
    icon: clock-outline
    source: {interval: 6h}

  - name: every-day
    type: time
    source:
      interval: 24h

  - name: tests-image
    type: docker-image
    icon: docker
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: govuk-coronavirus-business-volunteer-tests-image

  - name: govuk-coronavirus-services-tech-slack
    type: slack-notification
    source:
      url: https://hooks.slack.com/((slack_webhook_url))

jobs:
  - name: update-pipeline
    plan:
      - get: git-master
        trigger: true
      - set_pipeline: govuk-corona-business-volunteer-form
        file: git-master/concourse/pipeline.yml

  - name: build-tests-image
    serial: true
    build_logs_to_retain: 100
    plan:
      - get: every-day
        trigger: true
      - get: git-master-gems-dockerfile
        trigger: true
      - put: tests-image
        params:
          build: git-master-gems-dockerfile
          dockerfile: git-master-gems-dockerfile/concourse/Dockerfile

  - name: run-quality-checks
    serial: true
    plan:
      - get: tests-image
        passed:
          - build-tests-image
        trigger: true
      - get: git-master
        trigger: true
      - task: run-tests-task
        image: tests-image
        config:
          inputs:
            - name: git-master
          outputs:
            - name: committer-details
          platform: linux
          run:
            dir: git-master
            path: bash
            args:
              - -c
              - |
                set -eu
                service postgresql start
                su - postgres -c "psql -c \"create role root with createdb login password 'password';\""
                service redis-server start
                export TEST_DATABASE_URL="postgres://root:password@localhost:5432/coronavirus_business_volunteer_form_test"
                export RAILS_ENV=test
                bundle install
                bundle exec rails db:setup
                bundle exec rails db:migrate
                bundle exec rake

  - name: deploy-to-staging
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [run-quality-checks]
      - task: deploy-to-paas
        config:
        file: git-master/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: staging
          INSTANCES: 2
          WORKER_INSTANCES: 1
          CF_STARTUP_TIMEOUT: 5 # minutes
          REQUIRE_BASIC_AUTH: "true"
          BASIC_AUTH_PASSWORD: ((basic-auth-password))
          AWS_ACCESS_KEY_ID: ((aws-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
          SECRET_KEY_BASE: ((secret-key-base-staging))
          HOSTNAME: govuk-coronavirus-business-volunteer-form-stg
          SENTRY_DSN: https://((sentry-dsn))
          AWS_ERROR_PAGES_BUCKET_NAME: govuk-coronavirus-business-volunteer-error-pages-staging
          AWS_ASSETS_BUCKET_NAME: govuk-coronavirus-business-volunteer-assets-staging
          GOVUK_NOTIFY_TEMPLATE_ID: b9661b65-805c-4290-9428-2495f3427964
          NOTIFY_API_KEY: ((notify-api-key-stg))
        on_failure:
          put: govuk-coronavirus-services-tech-slack
          params:
            channel: '#govuk-corona-services-tech'
            username: 'Concourse (Business Volunteering Service)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Deploy to staging for the Business Volunteering service has failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: smoke-test-staging
    plan:
      - get: tests-image
        passed:
          - build-tests-image
      - get: git-master
        trigger: true
        passed: [deploy-to-staging]
      - task: smoke-test
        file: git-master/concourse/tasks/smoke-test.yml
        params:
          URL: 'https://govuk-coronavirus-business-volunteer-form-stg.cloudapps.digital/medical-equipment'
          MESSAGE: "Checks that the application deployed to staging is not serving HTTP error codes"
      - task: run-smoke-tests
        image: tests-image
        file: git-master/concourse/tasks/run-smoke-tests.yml
        params:
          TEST_URL: 'https://gds:((basic-auth-password))@govuk-coronavirus-business-volunteer-form-stg.cloudapps.digital'
        on_failure:
          put: govuk-coronavirus-services-tech-slack
          params:
            channel: '#govuk-corona-services-tech'
            username: 'Concourse (Business Volunteering Service)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Staging smoke tests for the Business Volunteering service have failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: deploy-to-prod
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [smoke-test-staging]
      - task: deploy-to-paas
        file: git-master/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: production
          INSTANCES: 10
          WORKER_INSTANCES: 1
          CF_STARTUP_TIMEOUT: 15 # minutes
          REQUIRE_BASIC_AUTH:
          BASIC_AUTH_PASSWORD: ((basic-auth-password))
          AWS_ACCESS_KEY_ID: ((aws-access-key-id-prod))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key-prod))
          AWS_ERROR_PAGES_BUCKET_NAME: govuk-coronavirus-business-volunteer-error-pages-prod
          SECRET_KEY_BASE: ((secret-key-base-prod))
          HOSTNAME: govuk-coronavirus-business-volunteer-form-prod
          SENTRY_DSN: https://((sentry-dsn))
          AWS_ASSETS_BUCKET_NAME: govuk-coronavirus-business-volunteer-assets-prod
          GOVUK_NOTIFY_TEMPLATE_ID: 94e7f169-6c10-487f-b9d2-4d03fc162a1e
          NOTIFY_API_KEY: ((notify-api-key-prod))
        on_failure:
          put: govuk-coronavirus-services-tech-slack
          params:
            channel: '#govuk-corona-services-tech'
            username: 'Concourse (Business Volunteering Service)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Deploy to production for the Business Volunteering service has failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME


  - name: smoke-test-prod
    plan:
      - get: git-master
        trigger: true
        passed: [deploy-to-prod]
      - get: tests-image
        passed:
          - build-tests-image
      - task: smoke-test
        file: git-master/concourse/tasks/smoke-test.yml
        params:
          URL: 'https://coronavirus-business-volunteers.service.gov.uk/medical-equipment'
          MESSAGE: "Checks that the application deployed to production is not serving HTTP error codes"
      - task: run-smoke-tests
        image: tests-image
        file: git-master/concourse/tasks/run-smoke-tests.yml
        params:
          TEST_URL: 'https://coronavirus-business-volunteers.service.gov.uk'
        on_failure:
          put: govuk-coronavirus-services-tech-slack
          params:
            channel: '#govuk-corona-services-tech'
            username: 'Concourse (Business Volunteering Service)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Production smoke tests for the Business Volunteering service have failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: export-form-responses-periodically
    plan:
      - get: git-master
      - get: every-six-hours
        trigger: true
      - task: export-form-responses
        file: git-master/concourse/tasks/export-form-responses.yml
        params:
          CF_SPACE: production
          SENTRY_DSN: https://((sentry-dsn))
