platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: govuk-coronavirus-business-volunteer-form-feature-tests
params:
  TEST_URL:
  RAILS_ENV: smoke_test
inputs:
  - name: govuk-coronavirus-business-volunteer-form
run:
  path: bundle
  dir: govuk-coronavirus-business-volunteer-form
  args: ['exec', 'rspec', 'spec/features']
