platform: linux
params:
  TEST_URL:
  RAILS_ENV: smoke_test
inputs:
  - name: git-master
run:
  dir: git-master
  path: sh
  args:
    - '-c'
    - |
      echo "Checking dependencies"
      bundle
      echo "Running smoke tests..."
      bundle exec rspec spec/features
