on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundle

    - run: sudo apt-get -yqq install libpq-dev
    - run: |
        bundle install --jobs 4 --retry 3 --deployment
        bundle exec rake db:create
        bundle exec rake db:migrate
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        DB_USERNAME: postgres
    - run: bundle exec rake
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        DB_USERNAME: postgres
        REDIS_HOST: redis
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        file: ./coverage/coverage.xml
