name: Run tests

on: [push, pull_request]

jobs:
  container-jobs:
    name: Pre-merge checks
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1

    - name: Install PostgreSQL 11 client
      run: sudo apt-get -yqq install libpq-dev

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundle

    - name: Build App
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        DB_USERNAME: postgres
      run: |
        bundle install --jobs 4 --retry 3 --deployment
        bundle exec rake db:create
        bundle exec rake db:migrate

    - name: Run Tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        DB_USERNAME: postgres
        REDIS_HOST: redis
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
      run: |
        bundle exec rake
